# Generated by Django 4.2.16 on 2024-09-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBooksRepresentation',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('meta', models.JSONField(default=dict)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('DELETED', 'DELETED'), ('BORROWED', 'BORROWED')], default='AVAILABLE', max_length=255)),
            ],
            options={
                'ordering': ['-_id', '-date_created', '-last_updated'],
                'abstract': False,
            },
        ),
    ]
